### ISSUE TITLE
iOS新人询问

### ISSUE THREAD

**Issue by liupy525** [zfdang/zSMTH#1]
你好，最近在学习iOS开发，发现了您的app代码，打算学习下，现在我遇到一个问题不明白，向您咨询：
zSMTH/libSMTH/SMTHURLConnection.h 文件里的所有声明是在哪里实现的啊？我搜索整个项目也没找到啊。。。
期待您的答复，谢谢！

**Comment by zfdang** [comment]
libSMTH_0.2.3.a, 使用的是水木提供的library.

**Comment by liupy525** [comment]
soga，谢谢哈
